spring.application.name=baymak-backend

spring.datasource.url=jdbc:mysql://localhost:3306/baymak?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Kumek9496

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

# JWT Configuration
# HMAC-SHA256 için minimum 32 byte (256 bit) gereklidir
# Daha güvenli olması için 64 byte (512 bit) önerilir
jwt.secret=MyVerySecureSecretKeyForJWTTokenGenerationMustBeAtLeast32BytesLongForHMACSHA256AlgorithmToWorkProperly
jwt.expiration=86400000
